### PR TITLE
Release 2.3.0

### PR DESCRIPTION
**Pull request by mahofficial**
Theme Switcher Updated to v2.0.3
- Complete Rewrite
- Support for Default Theme
- Support for Changing the Position of the Theme Selector
- Improved support for themes
- Switched from Cookies to LocalStorage
- Option to switch back to the default theme

vPanel ~Notifications~ Alert v1.0.1 Released
- Send ~Push Notifications~ Alerts to Logged-in Users
- Set delay in milliseconds to display alert after that delay
- Set Interval to automatically close ~notification~ alert after that interval
- Unique identifier to show ~notification~ alert only once to each user.
- Display to limited number of users (by list of username)
- Set custom icon, title and description for alert
- Close button to close the alert

Menu Item Changer v1.0.0 Released
- Add a new menu item with an icon, title, and link
- Modify default menu items icon, title, or link
- Remove default menu items
- Compatible with all themes available at [VistaPanel Themes](https://github.com/WybeNetwork/VistaPanel-Themes)
- Default Icons (Added by default [Font Awesome](https://fontawesome.com/v4/icons/))

Other 
- Deprecated Change Language Link Text Changer in favor of Menu Item Changer
- Deprecated Change Password Link Text Changer in favor of Menu Item Changer

### CODE REVIEW

**Comment by 4yx** [comment]
Please hold until I've written the docs for the element changer's new functionality, I'll do this as soon as I'm back in two-three hours and will then review as well.

**Comment by 4yx** [comment]
Just to confirm; I was waiting for a new release of vPanel Notifications before reviewing; will there be a change, or will it be published as is?

**Comment by mahofficial** [comment]
> Just to confirm; I was waiting for a new release of vPanel Notifications before reviewing; will there be a change, or will it be published as is?

I'll update it in my free time.

**Comment by 4yx** [comment]
> > Just to confirm; I was waiting for a new release of vPanel Notifications before reviewing; will there be a change, or will it be published as is?
> 
> I'll update it in my free time.



> > Just to confirm; I was waiting for a new release of vPanel Notifications before reviewing; will there be a change, or will it be published as is?
> 
> I'll update it in my free time.

Okay! Do you plan to update it in this or a new release (I mean, is this ready or should I wait?)

**Comment by mahofficial** [comment]
> > > Just to confirm; I was waiting for a new release of vPanel Notifications before reviewing; will there be a change, or will it be published as is?
> > 
> > 
> > I'll update it in my free time.
> 
> > > Just to confirm; I was waiting for a new release of vPanel Notifications before reviewing; will there be a change, or will it be published as is?
> > 
> > 
> > I'll update it in my free time.
> 
> Okay! Do you plan to update it in this or a new release (I mean, is this ready or should I wait?)

It's not ready yet.

**Comment by mahofficial** [comment]
@4yx Notification system is now changed to alert system

**Review by 4yx — APPROVED** [review]
Everything's good. We'll merge some updates later.

**Pull request merged**
